version: '2.0'
services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - "./node/app:/src/app"
    ports:
      - "8080:3000" 
  
  # couchdb:
  #   build:
  #     context: ./couchdb
  #     dockerfile: Dockerfile
  #   image: couchdb:1.6.1
  #   volumes:
  #     - ./etc:/usr/local/etc/couchdb/local.d
  #     - ./lib:/usr/local/var/lib/couchdb
  #   ports:
  #     - "5984:5984"